// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TikTokEcoBelarus.Infrastructure;

#nullable disable

namespace TikTokEcoBelarusPipeline.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.ScoringRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxMatches")
                        .HasColumnType("integer");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchContext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.ToTable("ScoringRules", (string)null);
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.ScoringRuleThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinMatchCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("ScoreBonus")
                        .HasColumnType("numeric");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScoringRuleThresholds", (string)null);
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.SearchQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SearchQueries", (string)null);
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.TrackedChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastCommentCount")
                        .HasColumnType("integer");

                    b.Property<int?>("LastVideoCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("TrackedChannels", (string)null);
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.TrackedChannelVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CommentCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ShareCount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TrackedChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("VideoCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TrackedChannelId", "VideoId")
                        .IsUnique();

                    b.ToTable("TrackedChannelVideos", (string)null);
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.Video", b =>
                {
                    b.Property<string>("VideoId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorBio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorNickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorUniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BelarusScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<long>("CommentCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EcoScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Hashtags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string[]>("MatchedKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScoreBreakdown")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ShareCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("VideoId");

                    b.ToTable("Videos", (string)null);
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.VideoSearchQueryLink", b =>
                {
                    b.Property<string>("VideoId")
                        .HasColumnType("text");

                    b.Property<Guid>("SearchQueryId")
                        .HasColumnType("uuid");

                    b.HasKey("VideoId", "SearchQueryId");

                    b.HasIndex("SearchQueryId");

                    b.ToTable("VideoSearchQueryLinks", (string)null);
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.TrackedChannelVideo", b =>
                {
                    b.HasOne("TikTokEcoBelarus.Domain.Entities.TrackedChannel", "Channel")
                        .WithMany("Videos")
                        .HasForeignKey("TrackedChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.VideoSearchQueryLink", b =>
                {
                    b.HasOne("TikTokEcoBelarus.Domain.Entities.SearchQuery", "SearchQuery")
                        .WithMany("VideoLinks")
                        .HasForeignKey("SearchQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TikTokEcoBelarus.Domain.Entities.Video", "Video")
                        .WithMany("SearchQueryLinks")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchQuery");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.SearchQuery", b =>
                {
                    b.Navigation("VideoLinks");
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.TrackedChannel", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("TikTokEcoBelarus.Domain.Entities.Video", b =>
                {
                    b.Navigation("SearchQueryLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
